scrollback_lines            5000
confirm_os_window_close     -1
font_family                 FiraCode Nerd Font
disable_ligatures           cursor
cursor_shape                block
cursor_text_color           background
# shell_integration           no-cursor
cursor_blink_interval       0
window_alert_on_bell        yes
bell_on_tab                 yes
enabled_layouts             *
window_border_width         1
window_margin_width         1
window_padding_width        1
allow_remote_control        yes
confirm_os_window_close     -1
repaint_delay               2
input_delay                 0
# linux_display_server      x11
map ctrl+tab send_text normal,application \x1b[9;5u
map ctrl+shift+tab send_text normal,application \x1b[9;6u
