edge top
# lines 20  # or 25% for relative height
# columns 100
# background_opacity 0.9
# hide_on_focus_loss yes
# margin_left 20%
# margin_right 20%
# kitty_override font_size=14  # kitty.conf overrides
