# -----------------------------------------------------
# General window layout and colors
# name: "Default"
# -----------------------------------------------------

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 1
    col.active_border = $primary $on_primary 90deg
    col.inactive_border = $on_primary
    layout = scrolling
    resize_on_border = true
}

scrolling {
    focus_fit_method = 1
    direction = left
}
