# Add your additional Hyprland configurations here


# -----------------------------------------------------
# Environment Variables
# name: "Chinese"
# -----------------------------------------------------
env = GTK_IM_MODULE,wayland
env = QT_IM_MODULE,fcitx
env = XMODIFIERS,"@im=fcitx"
env = SDL_IM_MODULE,fcitx
env = GLFW_IM_MODULE,fcitx

# Directories
env = ML4W_PERSONAL_DIR,/home/chachi/Documents/personal
env = ML4W_PROJECTS_DIR,/home/chachi/Documents/projects
env = ML4W_WALLPAPERS_DIR,/home/chachi/.config/ml4w/wallpapers
env = ML4W_UNIVERSITY_DIR,~/obsidian-vault/uni

# SUPER + forward button: run something
# bind = SUPER, mouse:277, exec, notify-send "MX forward button pressed"
bind = , mouse:277, killactive

windowrule {
    name = wechat
    match:class = wechat
    float = true
    center = true
    pin = true
    # size = 730 800
}
