# Add your additional Hyprland configurations here

# -----------------------------------------------------
# Environment Variables
# name: "Default Apps"
# -----------------------------------------------------
env = BROWSER,brave
env = TERMINAL,kitty

# -----------------------------------------------------
# Environment Variables
# name: "Chinese"
# -----------------------------------------------------
env = GTK_IM_MODULE,wayland
env = QT_IM_MODULE,fcitx
env = XMODIFIERS,"@im=fcitx"
env = SDL_IM_MODULE,fcitx
env = GLFW_IM_MODULE,fcitx

# Directories
env = ML4W_PERSONAL_DIR,/home/chachi/Documents/personal
env = ML4W_PROJECTS_DIR,/home/chachi/Documents/projects
env = ML4W_UNIVERSITY_DIR,/home/chachi/Documents/uni
env = ML4W_WALLPAPERS_DIR,/home/chachi/.config/ml4w/wallpapers

# -----------------------------------------------------
# Environment Variables
# name: "Nvidia"
# -----------------------------------------------------
# env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia



# SUPER + forward button: run something
# bind = SUPER, mouse:277, exec, notify-send "MX forward button pressed"
bind = , mouse:277, killactive

windowrule {
    name = download-dialogue
    match:class = xdg-desktop-portal-gtk
    float = true
}

windowrule {
    name = wechat
    match:class = wechat
    float = true
    # center = true
    pin = true
    # size = 730 800
}

windowrule {
    name = wasistlos
    match:class = wasistlos
    float = true
    center = true
    pin = true
}

windowrule {
    name = borderless-on-fullscreen
    match:fullscreen = true
    border_size = 0
}

windowrule {
    name = librepods
    match:class = ^(me.kavishdevar.librepods)$
    float = true
    center = true
    pin = true
}

# Chinese input
exec-once = fcitx5 &

# Gnome Keyrings
# exec-once = dbus-update-activation-environment --all

# exec-once = gnome-keyring-daemon --start --components=secrets

# exec-once = nm-applet &

# exec-once = ~/.config/waybar/launch.sh

# NOTE: Trying to fix Network displays
# exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# ----------------------------------
# Custom Keybinds
# ----------------------------------
bind = $mainMod, S, exec, $HYPRSCRIPTS/screenshot.sh                                      # Take a screenshot
bind = $mainMod CTRL, F, exec, $HYPRSCRIPTS/screenshot.sh --instant                       # Take an instant full-screen screenshot
bind = $mainMod CTRL, S, exec, grimblast --notify copysave area                           # Take an instant area screenshot
bind = $mainMod SHIFT, S, exec, grimblast --notify copy area                              # Take an instant area screenshot and copy to clipboard

bind=  ALT, W, exec, qutebrowser

workspace = special:dropdown, on-created-empty:kitty --class kitty-dropdown
windowrule {
    name = kitty-dropdown
    match:class = ^(kitty-dropdown)$
    float = true
    move = (monitor_w/2-window_w/2) 0 # (monitor_width/2-window_width/2) 0
    size = 1000 600
}
bind = $mainMod, grave, exec, kitten quick-access-terminal

# Prevents all applications from requesting a maximized state FIXME:
windowrule = match:fullscreen_state_client 2 suppress_event maximize
