-- monitors_compat.lua
-- Parses a hyprlang monitors.conf generated by nwg-displays and applies
-- hl.monitor() calls using the Hyprland 0.55+ Lua API.
--
-- Usage: require("monitors_compat") in your hyprland.lua
-- (place this file next to hyprland.lua in ~/.config/hypr/)
--
-- nwg-displays emits transform as a separate directive, e.g.:
--   monitor=desc:Some Monitor,1920x1080@60,0x0,1.2
--   monitor=desc:Some Monitor,transform,3
-- This script merges such lines into the preceding monitor entry.
-- -- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- hl.monitor({
-- 	output = "",
-- 	mode = "preferred",
-- 	position = "auto",
-- 	scale = "1.0",
-- })

local M = {}

local MONITORS_CONF = (os.getenv("HOME") or "") .. "/.config/hypr/monitors.conf"

local function trim(s)
	return s:match("^%s*(.-)%s*$")
end

-- Split into at most `max` parts on commas; the last part absorbs remaining commas.
local function split_csv(s, max)
	local result = {}
	local remaining = s
	while #result < (max - 1) do
		local before, after = remaining:match("^([^,]*),(.*)")
		if not before then
			break
		end
		table.insert(result, trim(before))
		remaining = after
	end
	table.insert(result, trim(remaining))
	return result
end

local function parse_extra_flags(s, monitor)
	for raw in s:gmatch("([^,]+)") do
		local flag = trim(raw)
		if flag == "disabled" then
			monitor.disabled = true
		else
			local key, val = flag:match("^([%w_]+):(.+)$")
			if key and val then
				key = key:lower()
				if
					key == "transform"
					or key == "bitdepth"
					or key == "vrr"
					or key == "supports_wide_color"
					or key == "supports_hdr"
				then
					monitor[key] = tonumber(val) or val
				elseif
					key == "sdrbrightness"
					or key == "sdrsaturation"
					or key == "sdr_min_luminance"
					or key == "sdr_max_luminance"
					or key == "min_luminance"
					or key == "max_luminance"
					or key == "max_avg_luminance"
				then
					monitor[key] = tonumber(val) or val
				elseif key == "mirror" or key == "cm" or key == "icc" or key == "sdr_eotf" then
					monitor[key] = val
				else
					monitor[key] = tonumber(val) or val
				end
			end
		end
	end
end

-- Parse one "monitor = <value>" line.
-- Returns either a full monitor table, or a "patch" table when nwg-displays
-- emits a property-only line such as:  monitor=desc:Foo,transform,3
-- Patch tables have { _patch=true, output=..., <key>=<value> }.
local function parse_monitor_line(value)
	local fields = split_csv(value, 5)
	if #fields < 1 then
		return nil
	end

	local output = fields[1] or ""
	local f2 = fields[2] -- mode, OR a property keyword like "transform"
	local f3 = fields[3] -- position, OR the property value
	local f4 = fields[4] -- scale (may be nil)

	-- Detect nwg-displays property-only lines:
	--   monitor=<output>,transform,<n>
	--   monitor=<output>,disabled
	--   (potentially other single-property lines in future nwg-displays versions)
	local PROPERTY_KEYWORDS = {
		transform = true,
		disabled = true,
		mirror = true,
		bitdepth = true,
		vrr = true,
	}

	if f2 and PROPERTY_KEYWORDS[f2:lower()] then
		local patch = { _patch = true, output = output }
		local key = f2:lower()
		if key == "disabled" then
			patch.disabled = true
		else
			-- f3 is the value for this property
			local val = f3
			if key == "transform" or key == "bitdepth" or key == "vrr" then
				patch[key] = tonumber(val) or val
			else
				patch[key] = val
			end
		end
		return patch
	end

	-- Normal monitor line
	local monitor = { output = output }

	if f2 and f2 ~= "" then
		monitor.mode = f2
	end
	if f3 and f3 ~= "" then
		monitor.position = f3
	end
	if f4 and f4 ~= "" then
		monitor.scale = tonumber(f4) or f4
	end

	if fields[5] and fields[5] ~= "" then
		parse_extra_flags(fields[5], monitor)
	end

	return monitor
end

function M.load(path)
	path = path or MONITORS_CONF

	local file, err = io.open(path, "r")
	if not file then
		print("[monitors_compat] WARNING: could not open " .. path .. ": " .. (err or "unknown error"))
		return
	end

	-- Collect all parsed entries first so patches can be merged before
	-- any hl.monitor() calls are made.
	local entries = {} -- list of full monitor tables, keyed by position in list
	local by_output = {} -- output string -> index in entries, for patch merging

	for raw in file:lines() do
		local line = raw:gsub("#.*$", "")
		line = trim(line)

		if line ~= "" then
			local value = line:match("^[Mm]onitor%s*=%s*(.+)$")
			if value then
				local parsed = parse_monitor_line(value)
				if parsed then
					if parsed._patch then
						-- Merge into the most recent entry with the same output
						local idx = by_output[parsed.output]
						if idx then
							local target = entries[idx]
							for k, v in pairs(parsed) do
								if k ~= "_patch" and k ~= "output" then
									target[k] = v
								end
							end
						else
							-- No preceding entry found; apply as standalone patch
							-- (shouldn't happen with well-formed nwg-displays output,
							-- but handle gracefully)
							parsed._patch = nil
							table.insert(entries, parsed)
							by_output[parsed.output] = #entries
						end
					else
						table.insert(entries, parsed)
						by_output[parsed.output] = #entries
					end
				end
			end
		end
	end

	file:close()

	for _, mon in ipairs(entries) do
		hl.monitor(mon)
	end

	print("[monitors_compat] Applied " .. #entries .. " monitor rule(s) from " .. path)
end

M.load()

return M
