-- local aug = vim.api.nvim_create_augroup
-- local au  = vim.api.nvim_create_autocmd
-- local defer = vim.schedule
--
-- -- Treesitter — eager (syntax highlighting needed immediately)
-- vim.pack.add({
--   'https://github.com/nvim-treesitter/nvim-treesitter',
--   'https://github.com/nvim-treesitter/nvim-treesitter-textobjects',
--   'https://github.com/windwp/nvim-ts-autotag',
-- })
-- require('nvim-treesitter.configs').setup({
--   ensure_installed = { 'lua', 'python', 'typescript', 'rust', 'c', 'cpp' },
--   highlight      = { enable = true },
--   textobjects    = { select = { enable = true, lookahead = true } },
--   autotag        = { enable = true },
-- })
--
-- -- Autopairs — on file open
-- au({ 'BufReadPre', 'BufNewFile' }, {
--   group = aug('LazyLoad_Autopairs', { clear = true }), once = true,
--   callback = function()
--     vim.pack.add({ 'https://github.com/windwp/nvim-autopairs' })
--     require('nvim-autopairs').setup({})
--   end,
-- })
--
-- -- Surround, Flash, better-escape — deferred (were VeryLazy)
-- defer(function()
--   vim.pack.add({
--     'https://github.com/kylechui/nvim-surround',
--     'https://github.com/folke/flash.nvim',
--     'https://github.com/max397574/better-escape.nvim',
--   })
--   require('nvim-surround').setup({})
--   require('flash').setup({})
--   require('better_escape').setup({ default_mappings = true })
-- end)
--
-- -- Guess indent — on file open
-- au({ 'BufReadPre', 'BufNewFile' }, {
--   group = aug('LazyLoad_Indent', { clear = true }), once = true,
--   callback = function()
--     vim.pack.add({ 'https://github.com/nmac427/guess-indent.nvim' })
--     require('guess-indent').setup({})
--   end,
-- })
--
-- -- Aerial (outline) — on file open
-- au({ 'BufReadPre', 'BufNewFile' }, {
--   group = aug('LazyLoad_Aerial', { clear = true }), once = true,
--   callback = function()
--     vim.pack.add({ 'https://github.com/stevearc/aerial.nvim' })
--     require('aerial').setup({})
--   end,
-- })
--
-- -- Smart splits — deferred
-- defer(function()
--   vim.pack.add({ 'https://github.com/mrjones2014/smart-splits.nvim' })
--   require('smart-splits').setup({})
-- end)
