# --password-store=basic
# --enable-chrome-browser-cloud-management
# --ozone-platform=wayland 
# --enable-features=TouchpadOverscrollHistoryNavigation
--enable-features=UseOzonePlatform
--ozone-platform-hint=auto
--enable-hw-overlay
