--ozone-platform=wayland
# --use-angle=vulkan
# --enable-features=WaylandLinuxDrmSyncobj,VaapiVideoDecodeLinuxGL
--disable-features=UseChromeOSDirectVideoDecoder
# --use-gl=egl
# --ozone-platform-hint=auto
# --enable-hw-overlay
# --enable-features=WaylandLinuxDrmSyncobj,VaapiVideoDecodeLinuxGL,VaapiVideoDecoder,VaapiIgnoreDriverChecks,UseOzonePlatform
# --use-angle=vulkan
# --enable-gpu-rasterization
# --enable-zero-copy
#
# --enable-features=WaylandLinuxDrmSyncobj,VaapiVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxGL
# --use-gl=egl
# --enable-zero-copy
# --ignore-gpu-blocklist
