# -----------------------------------------------------
# Monitor Setup
# name: "Default"
# -----------------------------------------------------

# monitor=,preferred,auto,1
monitor=eDP-1,1920x1080@60.02,3640x437,1.0
monitor=DP-1,2560x1440@59.95,1080x77,1.0
monitor=HDMI-A-1,1920x1080@60.0,0x0,1.0
monitor=HDMI-A-1,transform,3
